// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Dv3wNjBwkefxpKwRdZttnRJczDtONK4',
    appId: '1:126981571024:web:00af2a484a11a76abd39d5',
    messagingSenderId: '126981571024',
    projectId: 'locallink-995a5',
    authDomain: 'locallink-995a5.firebaseapp.com',
    storageBucket: 'locallink-995a5.firebasestorage.app',
    measurementId: 'G-FS2QVEWMYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5g8flHbKSgSotjo3APx4XUJqckVTlbTk',
    appId: '1:126981571024:android:3d6cd6bf4119bee6bd39d5',
    messagingSenderId: '126981571024',
    projectId: 'locallink-995a5',
    storageBucket: 'locallink-995a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApwXO62bvgmF7OdscIs4uGkgYSftsX-Jg',
    appId: '1:126981571024:ios:4bd4e6b2b8e78485bd39d5',
    messagingSenderId: '126981571024',
    projectId: 'locallink-995a5',
    storageBucket: 'locallink-995a5.firebasestorage.app',
    androidClientId: '126981571024-gm2hkrd7b4692jk884hd51gena3qe4a1.apps.googleusercontent.com',
    iosClientId: '126981571024-p0fsgkrrkb3865j6f37utjiks4f29fk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.locallinkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApwXO62bvgmF7OdscIs4uGkgYSftsX-Jg',
    appId: '1:126981571024:ios:4bd4e6b2b8e78485bd39d5',
    messagingSenderId: '126981571024',
    projectId: 'locallink-995a5',
    storageBucket: 'locallink-995a5.firebasestorage.app',
    androidClientId: '126981571024-gm2hkrd7b4692jk884hd51gena3qe4a1.apps.googleusercontent.com',
    iosClientId: '126981571024-p0fsgkrrkb3865j6f37utjiks4f29fk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.locallinkFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1Dv3wNjBwkefxpKwRdZttnRJczDtONK4',
    appId: '1:126981571024:web:3d04edc90f989c28bd39d5',
    messagingSenderId: '126981571024',
    projectId: 'locallink-995a5',
    authDomain: 'locallink-995a5.firebaseapp.com',
    storageBucket: 'locallink-995a5.firebasestorage.app',
    measurementId: 'G-Q4PLT9MNM4',
  );
}
